[package]
name = "rustdid"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
base64 = "0.22.1"
futures-lite = "2.5.0"
miette = { version = "7.4.0", features = ["fancy"] }
smol = "2.0.2"
